export const DEFAULT_CURRENCIES = [
  "btc", "eth", "rub","eur", "sgd","cad","mxn", "usd",
  "krw","idr","try","sar","sek","ngn","pln","brl",
  "ars","nok","twd","irr","aed","cop","thb","zar",
  "dkk","myr","ils","hkd","egp","php","clp",
  "pkr","iqd","dzd","kzt","qar","czk","pen","ron",
  "vnd","bdt","huf","uah","aoa","mad","omr","cuc",
  "byr","azn","lkr","sdg","syp","mmk","dop","uzs",
  "kes","gtq","ury","hrv","mop","etb","crc","tzs",
  "tmt","tnd","pab","lbp","rsd","lyd","ghs","yer",
  "bob","bhd","cdf","pyg","ugx","svc","ttd","afn",
  "npr","hnl","bih","bnd","isk","khr","gel","mzn",
  "bwp","pgk","jmd","xaf","nad","all","ssp","mur",
  "mnt","nio","lak","mkd","amd","mga","xpf","tjs",
  "htg","bsd","mdl","rwf","kgs","gnf","srd","sll",
  "xof","mwk","fjd","ern","szl","gyd","bif","kyd",
  "mvr","lsl","lrd","cve","djf","scr","sos","gmd",
  "kmf","std","xrp","aud","bgn","jod","gbp",
  "ltc","nzd","jpy","cny","chf","inr"
];
