export enum Fields {
  VAULT = 'mnemonic-vault',
  LOCK_TIME = 'time_before_lock',
  WALLET = 'wallet-identities',
  NETWROK_CONFIG = 'network-config',
  NETWROK_SELECTED = 'network-selected',
  TRANSACTIONS = 'transactions',
  CONFIRM_TRANSACTIONS = 'confirm-transactions',
  CONFIRM_SIGN_MESSAGE = 'confirm-sign-message',
  BADGE_COUNTER = 'badge-control',
  UI_THEME = 'ui-theme',
  SELECTED_CURRENCY = 'selected-currency',
  LOCALE = 'locale',
  NETWORK_DOWNGRADE = 'network-downgrade-flag',
  PERIOD_OFFSET = 'period-offset',
  PHISHING_DETECTION = 'phishing-detection-enabled',
  CONNECTIONS_LIST = 'dapp-connections-list',
  CONNECT_DAPP = 'for-connect-app',
  CONTACTS_LIST = 'contacts-list',
  TOKENS = 'tokens-list',
  PERIOD = 'current-period',
  GAS = 'gas-config'
}
